"""
cnn_model.py — CNN loader (MedicalNet ResNet-18, TorchScript)

Trained on mwp1 maps generated by deepmriprep (not by SPM12 — the change is
documented in config.py and the Dockerfile). Fold 3 = best individual fold.

IMPORTANT: the .pt must be generated with `torch.jit.script(model)`, NOT
with `torch.jit.trace(model, dummy)`. The trace path introduced a systematic
bias of ~0.062 that reclassified 50% of positive predictions as "control"
(see config.py for details).

EXACT TRAINING PREPROCESSING (GMVolumeDataset._load_and_resize):
  1. Load .nii.gz with nibabel
  2. nilearn.image.resample_img with target_affine=np.diag([1.9, 1.9, 1.9, 1])
     and target_shape=(96, 96, 96)
  3. Normalize: clip to the 99th percentile, then divide by that value
  4. Add batch and channel dims → (1, 1, 96, 96, 96)

NOTE: the 4x4 target_affine with translation = 0 literally reproduces the
training notebook code (Colab deepmriprep_3DCNN_VBM_Epilepsy.ipynb).
DO NOT modify — a "centered" grid fix would break equivalence with training.

Clinical threshold: 0.6875 (optimized for Specificity >= 0.85, fold 3)
"""

import numpy as np
import nibabel as nib
import torch
from pathlib import Path
from nilearn import image

from app.config import CNN_MODEL_PATH, CNN_CONFIG, DEVICE


# ─── Singleton ───────────────────────────────────────────────────────────────
_model = None


def get_model() -> torch.jit.ScriptModule:
    global _model
    if _model is None:
        _model = _load_model()
    return _model


def _load_model() -> torch.jit.ScriptModule:
    if not CNN_MODEL_PATH.exists():
        raise FileNotFoundError(
            f"Modelo CNN no encontrado: {CNN_MODEL_PATH}\n"
            "Copia el .pt re-trazado en CPU del notebook deepmriprep_3dcnn a "
            "backend/models/deepmriprep_cnn_fold3.pt"
        )
    print(f"[CNN] Cargando TorchScript desde {CNN_MODEL_PATH.name} → {DEVICE.upper()}")
    model = torch.jit.load(str(CNN_MODEL_PATH), map_location=DEVICE)
    model.eval()
    print("[CNN] Modelo cargado OK")
    return model


# ─── Preprocessing (exact replica of the training Dataset) ───────────────────

def preprocess_gm_map(gm_map_path: Path) -> torch.Tensor:
    """
    Preprocess a GM map (mwp1) for inference.
    Replicates GMVolumeDataset._load_and_resize from the training notebook.

    Args:
        gm_map_path: Path to the mwp1*.nii.gz produced by deepmriprep

    Returns:
        float32 tensor of shape (1, 1, 96, 96, 96) ready for inference
    """
    target_shape   = CNN_CONFIG["input_shape"]          # (96, 96, 96)
    vox_size       = CNN_CONFIG["target_affine"]        # [1.9, 1.9, 1.9]
    target_affine  = np.diag([*vox_size, 1]).astype(np.float64)

    # 1. Load image (supports .nii and .nii.gz)
    img = nib.load(str(gm_map_path))

    # 2. Resample — same method as in training
    img_resized = image.resample_img(
        img,
        target_affine=target_affine,
        target_shape=target_shape,
        interpolation='linear'
    )
    data = img_resized.get_fdata(dtype=np.float32)

    # 3. Normalize: clip p99 and divide — identical to the Dataset
    p99 = float(np.percentile(data, 99))
    if p99 > 0:
        data = np.clip(data, 0, p99) / p99
    else:
        raise ValueError(
            f"El mapa GM parece estar vacío (p99 ≈ 0): {gm_map_path.name}"
        )

    # 4. Add batch and channel dims → (1, 1, 96, 96, 96)
    tensor = torch.from_numpy(data[np.newaxis, np.newaxis, ...]).to(DEVICE)
    return tensor


# ─── Inference ───────────────────────────────────────────────────────────────

def predict(gm_map_path: Path) -> dict:
    """
    Run CNN inference on a GM map.

    Uses the clinical threshold 0.6875 (optimized for Spec >= 0.85 on fold 3)
    instead of the standard 0.5 threshold.

    Returns:
        dict with prob_epilepsy, prob_control, prediction, confidence,
        and threshold_used.
    """
    model     = get_model()
    tensor    = preprocess_gm_map(gm_map_path)
    threshold = CNN_CONFIG["clinical_threshold"]  # 0.6875

    with torch.no_grad():
        output = model(tensor)                           # (1, 2)
        probs  = torch.softmax(output, dim=1).squeeze()  # (2,)

    prob_control  = float(probs[0].cpu())
    prob_epilepsy = float(probs[1].cpu())

    # Prediction with the clinical threshold (not 0.5)
    prediction = "epilepsy" if prob_epilepsy >= threshold else "control"
    confidence = prob_epilepsy if prediction == "epilepsy" else prob_control

    return {
        "prob_epilepsy":   round(prob_epilepsy, 4),
        "prob_control":    round(prob_control,  4),
        "prediction":      prediction,
        "confidence":      round(confidence, 4),
        "threshold_used":  threshold,
    }


# ─── Model metrics (fold 3 — best individual fold) ───────────────────────────
# Computed in Colab over 156 validation subjects (87 patients + 69 controls).
# CV stats are the average across the 5 folds (fold 0..4).
CNN_MODEL_METRICS = {
    # Fold 3 (representative — best individual AUC)
    "auc":               0.7968,
    "sensitivity":       0.5581,
    "specificity":       0.8841,
    "accuracy":          0.7211,   # balanced accuracy fold 3
    "f1_macro":          0.7011,
    "clinical_threshold": 0.6875,
    "fold":              3,

    # 5-fold CV average (for the full thesis report)
    "auc_cv_mean":       0.6846,
    "auc_cv_std":        0.1048,
    "sens_cv_mean":      0.310,
    "sens_cv_std":       0.198,
    "spec_cv_mean":      0.896,
    "spec_cv_std":       0.054,
}
