// Minimal HTTP client against the FastAPI backend.
// Uses relative /api/... paths — Vite proxy (dev) and Nginx (prod) route them.

const API_BASE = '/api/v1';

// The backend expects ModelType ∈ { deepmriprep, nnunet }.
// The frontend ids match 1:1 with the backend ids.
const MODEL_ID_MAP = {
  deepmriprep: 'deepmriprep',
  nnunet: 'nnunet',
};

const apiModelId = (frontId) => MODEL_ID_MAP[frontId] || frontId;

const parseError = async (response) => {
  try {
    const body = await response.json();
    return body.detail || body.message || `HTTP ${response.status}`;
  } catch {
    return `HTTP ${response.status} ${response.statusText}`;
  }
};

// POST /analyze — multipart with file + metadata.
// Returns { job_id, message }.
export const postAnalyze = async (file, info, frontendModelId) => {
  const form = new FormData();
  form.append('file', file);
  form.append('test_name', info.test);
  form.append('model', apiModelId(frontendModelId));
  if (info.patient) form.append('patient_name', info.patient);
  if (info.notes) form.append('notes', info.notes);
  form.append('use_robex', info.useRobex ? 'true' : 'false');

  const response = await fetch(`${API_BASE}/analyze`, {
    method: 'POST',
    body: form,
  });

  if (!response.ok) throw new Error(await parseError(response));
  return response.json();
};

// GET /status/{job_id} — a snapshot of the job state.
export const getStatus = async (jobId) => {
  const response = await fetch(`${API_BASE}/status/${jobId}`);
  if (!response.ok) throw new Error(await parseError(response));
  return response.json();
};

// URL to the .txt report generated by the backend (not downloaded here — the
// frontend uses its own localized genTxt in ResultsScreen).
export const getReportURL = (jobId) => `${API_BASE}/report/${jobId}`;

// URLs for the nnUNet viewer — NiiVue loads them directly via internal fetch.
// Both files are .nii.gz; the backend serves the loaded T1 and the binary
// mask produced by the segmentation model.
export const getT1URL   = (jobId) => `${API_BASE}/t1/${jobId}`;
export const getMaskURL = (jobId) => `${API_BASE}/mask/${jobId}`;

// Force-download the mask as a .nii.gz file ("Download mask" button).
export const downloadMask = async (jobId, suggestedName) => {
  const response = await fetch(getMaskURL(jobId));
  if (!response.ok) throw new Error(await parseError(response));
  const blob = await response.blob();
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = suggestedName || `mask_${jobId}.nii.gz`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(a.href);
};
